Updated the workflow for GitHub.

diff --git a/docker/linux/Dockerfile b/docker/linux/Dockerfile
--- a/docker/linux/Dockerfile
+++ b/docker/linux/Dockerfile
@@ -5,24 +5,17 @@ ENV VULKAN_VERSION=1.4.321.1
 
 WORKDIR /tmp/vulkan
 
-# Copy and extract the Vulkan SDK.
-RUN apt update && apt install -y xz-utils
+# Copy and extract the Vulkan SDK and keep only required
+# includes/libraries/binaries for a minimal CI/CD Vulkan SDK image.
 COPY vulkansdk-linux-x86_64-$VULKAN_VERSION.tar.xz .
-RUN tar -xf ./vulkansdk-linux-x86_64-$VULKAN_VERSION.tar.xz
-
-# Keep only required includes/libraries/binaries for a minimal CI/CD Vulkan SDK image.
-RUN mkdir -p /minimal-sdk/bin /minimal-sdk/lib /minimal-sdk/include && \
+RUN apt-get update && apt-get install -y xz-utils && \
+    tar -xf ./vulkansdk-linux-x86_64-$VULKAN_VERSION.tar.xz && \
+    mkdir -p /minimal-sdk/bin /minimal-sdk/lib /minimal-sdk/include && \
     cp    ./$VULKAN_VERSION/x86_64/bin/glslc                 /minimal-sdk/bin && \
     cp -r ./$VULKAN_VERSION/x86_64/include                   /minimal-sdk     && \
     cp    ./$VULKAN_VERSION/x86_64/lib/libshaderc_shared.so* /minimal-sdk/lib && \
-    cp    ./$VULKAN_VERSION/x86_64/lib/libvulkan.so*         /minimal-sdk/lib
-
-# # Install Vulkan SDK.
-# ## Copy and extract the vulkan sdk into the image.
-# COPY vulkansdk-linux-x86_64-$VULKAN_VERSION.tar.xz .
-# RUN mkdir -p ./vulkan && \
-#     tar -xf ./vulkansdk-linux-x86_64-$VULKAN_VERSION.tar.xz -C ./vulkan && \
-#     rm ./vulkansdk-linux-x86_64-$VULKAN_VERSION.tar.xz
+    cp    ./$VULKAN_VERSION/x86_64/lib/libvulkan.so*         /minimal-sdk/lib && \
+    rm -rf vulkansdk-linux-x86_64-$VULKAN_VERSION.tar.xz ./$VULKAN_VERSION
 
 
 # Stage 2: Final Vulkan image.
@@ -34,15 +27,44 @@ ENV DEBIAN_FRONTEND=noninteractive
 ENV WORKFLOW_USER=runner
 
 # Update and install packages.
-RUN apt update && apt install -y mesa-vulkan-drivers && rm -rf /var/lib/apt/lists/*
-RUN useradd -m -u 1001 $WORKFLOW_USER
+RUN apt-get update && apt-get install -y --no-install-recommends \
+    adduser \
+    python3 \
+    python3-pip \
+    python-is-python3 \
+    pkgconf \
+    ninja-build && \
+    adduser --disabled-password --gecos "" $WORKFLOW_USER && \
+    apt-get purge -y --auto-remove adduser && \
+    rm -rf /var/lib/apt/lists/* && \
+    python -m pip install --cache-dir=/tmp/pipcache \
+        conan==2.19.1 \
+        cmake>=3.29 \
+        --no-cache-dir --break-system-packages && \
+    rm -rf /root/.cache/pip
 
 # Create a non-root user and working directory.
 USER $WORKFLOW_USER
 WORKDIR /home/$WORKFLOW_USER/vulkan-app
 
 # Copy only minimal Vulkan SDK.
-COPY --from=builder /minimal-sdk /home/$WORKFLOW_USER/vulkan-sdk
+COPY --chown=$WORKFLOW_USER --from=builder /minimal-sdk /home/$WORKFLOW_USER/vulkan-sdk
+
+# Set the Vulkan SDK environment variables.
+ENV VULKAN_SDK=/home/$WORKFLOW_USER/vulkan-sdk
+ENV PATH=$VULKAN_SDK/bin:$PATH
+ENV LD_LIBRARY_PATH=$VULKAN_SDK/lib
+ENV PKG_CONFIG_PATH=$VULKAN_SDK/lib/pkgconfig/
+
+HEALTHCHECK CMD [ "sh", "-c", 'if [ ! -x "$VULKAN_SDK/bin/glslc" ]; then echo "glslc missing"; exit 1; fi' ]
+
+
+# # Install Vulkan SDK.
+# ## Copy and extract the vulkan sdk into the image.
+# COPY vulkansdk-linux-x86_64-$VULKAN_VERSION.tar.xz .
+# RUN mkdir -p ./vulkan && \
+#     tar -xf ./vulkansdk-linux-x86_64-$VULKAN_VERSION.tar.xz -C ./vulkan && \
+#     rm ./vulkansdk-linux-x86_64-$VULKAN_VERSION.tar.xz
 
 # Strip the Vulkan SDK from unnecessary files to minimize the image size.
 # ENV VULKAN_x64_DIR=./vulkan/$VULKAN_VERSION/x86_64
@@ -62,15 +84,8 @@ COPY --from=builder /minimal-sdk /home/$WORKFLOW_USER/vulkan-sdk
 #     $VULKAN_LIB_DIR/libdx*.* \
 #     lib/libdxc*.*
 
-## Set the Vulkan SDK environment variables.
-ENV VULKAN_SDK=/home/$WORKFLOW_USER/vulkan-sdk
-ENV PATH=$VULKAN_SDK/bin:$PATH
-ENV LD_LIBRARY_PATH=$VULKAN_SDK/lib
-ENV PKG_CONFIG_PATH=$VULKAN_SDK/lib/pkgconfig/
 # ENV VULKAN_SDK=/home/$WORKFLOW_USER/vulkan-app/vulkan/$VULKAN_VERSION/x86_64
 # ENV PATH=$VULKAN_SDK/bin:$PATH
 # ENV LD_LIBRARY_PATH=$VULKAN_SDK/lib
 # ENV VK_LAYER_PATH=$VULKAN_SDK/share/vulkan/explicit_layer.d
 # ENV PKG_CONFIG_PATH=$VULKAN_SDK/lib/pkgconfig/
-
-CMD ["bash"]
